# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'stockcomputer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# Pods for stockcomputer
pod 'Firebase'
pod 'JGProgressHUD'
pod 'CVCalendar', '~> 1.6.2'
pod 'GCCalendar'
pod 'FSCalendar'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'Firebase/Auth'
pod 'Alamofire', '~> 4.0.0-beta.4'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Toaster'
pod 'VpadnSDK'
pod 'AdMobMediationAdapterVpadn'

pod 'Kanna', '~> 4.0.0'
pod 'Mapbox-iOS-SDK', '~> 5.4'
pod 'Firebase/InAppMessagingDisplay'
pod 'Instabug'
pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'
pod 'Siren'
pod 'JJFloatingActionButton'
pod 'SwiftSoup'
pod 'MarqueeLabel'
pod 'Firebase/Crashlytics'
pod 'Firebase/Performance'
pod 'Firebase/Analytics'
pod 'LLCycleScrollView' 
pod 'SwiftyStoreKit'

pod 'GoogleSignIn'
pod 'Firebase/Messaging'
pod 'Firebase/InAppMessaging'
pod 'CLImagePickerTool'
pod 'YoutubePlayerView'
   pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
pod 'SideMenu'
end
